# docker-compose.yml
version: '3'
services:
  scraper:
    build: .
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
  monitor:
    image: prom/prometheus
    ports:
      - "9090:9090"